/*
 * 码云 Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.3.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package gitee

// Tag 列出仓库所有的tags
type Tag struct {
	Name    string    `json:"name,omitempty"`
	Message string    `json:"message,omitempty"`
	Commit  TagCommit `json:"commit"`
}

type TagCommit struct {
	Sha  string `json:"sha"`
	Date string `json:"date"`
}
